FROM node:lts-alpine as build
COPY ["./.env", "./.env.production", "./index.html", "./package*.json", "./tsconfig*.json", "./vite.config.ts", "./"]
COPY ./src/ledger-es-ui ./src/ledger-es-ui/
RUN npm ci
RUN npm run build

FROM nginx:stable-alpine
COPY ./public /usr/share/nginx/html
COPY --from=build /dist /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
