FROM node:lts-alpine as build
COPY ["./index.html", "./package*.json", "./tsconfig*.json", "./vite.config.ts", "./"]
COPY ./src/ledger-es-ui ./src/ledger-es-ui/
RUN npm ci
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build /dist /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
