version: '3.8'
name: ledger-es

services:
  eventstore.db:
    image: eventstore/eventstore:22.10.1-buster-slim
    hostname: eventdb.ledger-es.local
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    healthcheck:
      test: curl --fail --insecure https://localhost:2113/health/live || exit 1
      interval: 5s
      timeout: 5s
      retries: 24
    ports:
      - 1113:1113
      - 2113:2113
      - 8081:2113
    networks:
      ledger-es-default:
        ipv4_address: 192.168.1.2
    volumes:
      - ./volumes/eventstore.db/data:/var/lib/eventstore
      - ./volumes/eventstore.db/logs:/var/log/eventstore
  rabbitmq:
    image: rabbitmq:3.11-management
    hostname: msgbus.ledger-es.local
    environment:
      - "RABBITMQ_DEFAULT_USER=user"
      - "RABBITMQ_DEFAULT_PASS=password"
      - "RABBITMQ_SECURE_PASSWORD=no"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 2s
      timeout: 5s
      retries: 20
      start_period: 7s
    ports:
      - 1883:1883
      - 5672:5672
      - 15672:15672
      - 8082:15672
    networks:
      ledger-es-default:
        ipv4_address: 192.168.1.3
    volumes:
      - ./volumes/rabbitmq/etc/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./volumes/rabbitmq/etc/20_ledger-es.conf:/etc/rabbitmq/conf.d/20_ledger-es.conf
      - ./volumes/rabbitmq/data:/var/lib/rabbitmq

networks:
  ledger-es-default:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: '192.168.1.1'
