version: '3.8'
name: ledger-es

services:
  eventstore.db:
    image: eventstore/eventstore:22.10.1-buster-slim
    hostname: eventdb.ledger-es.local
    environment:
      EVENTSTORE_CLUSTER_SIZE: "1"
      EVENTSTORE_RUN_PROJECTIONS: "All"
      EVENTSTORE_START_STANDARD_PROJECTIONS: "true"
      EVENTSTORE_EXT_TCP_PORT: "1113"
      EVENTSTORE_HTTP_PORT: "2113"
      EVENTSTORE_INSECURE: "true"
      EVENTSTORE_ENABLE_EXTERNAL_TCP: "true"
      EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP: "true"
    healthcheck:
      test: curl --fail http://localhost:2113/health/live || exit 1
      interval: 5s
      timeout: 5s
      retries: 24
    ports:
      - 1113:1113
      - 2113:2113
      - 8081:2113
    networks:
      ledger-es-default:
        ipv4_address: 192.168.1.2
    volumes:
      - ./volumes/eventstore.db/data:/var/lib/eventstore
      - ./volumes/eventstore.db/logs:/var/log/eventstore
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: db.ledger-es.local
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "X13ppP2prRi6fPmW"
      MSSQL_PID: "Developer"
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $$SA_PASSWORD -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
    ports:
      - 1434:1433
    networks:
      ledger-es-default:
        ipv4_address: 192.168.1.3
    volumes:
      - ./volumes/mssql/data:/var/opt/mssql/data
      - ./volumes/mssql/log:/var/opt/mssql/log
      - ./volumes/mssql/secrets:/var/opt/mssql/secrets
  ledger-es-api:
    build:
      dockerfile: ./Dockerfile.Api
    hostname: api.ledger-es.local
    environment:
      ConnectionStrings__EventStore: "esdb://192.168.1.2:2113?tls=false"
      ConnectionStrings__SqlServer: "Data Source=192.168.1.3;Initial Catalog=ledger-es;User Id=sa;Password=X13ppP2prRi6fPmW;Trust Server Certificate=true;"
    ports:
      - 8082:80
      - 8083:443
    networks:
      ledger-es-default:
        ipv4_address: 192.168.1.4
    depends_on:
      eventstore.db:
        condition: service_healthy
      mssql:
        condition: service_healthy
  ledger-es-ui:
    build:
      dockerfile: ./Dockerfile.Ui
    hostname: ui.ledger-es.local
    ports:
     - 8080:80
    networks:
      ledger-es-default:
        ipv4_address: 192.168.1.5
    depends_on:
      ledger-es-api:
        condition: service_healthy

networks:
  ledger-es-default:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: '192.168.1.1'
