FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["./src/Js.LedgerEs", "./"]
RUN dotnet restore ./Js.LedgerEs.csproj
RUN dotnet publish ./Js.LedgerEs.csproj --no-restore -f net7.0 -c Release -o /publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=build /publish .
ENTRYPOINT ["dotnet", "Js.LedgerEs.dll"]
